# Generated by Django 2.2.3 on 2019-07-11 21:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0003_auto_20190710_1256'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='venta',
            name='cantidad',
        ),
        migrations.RemoveField(
            model_name='venta',
            name='producto',
        ),
        migrations.RemoveField(
            model_name='venta',
            name='total',
        ),
    ]
