# Generated by Django 2.2.3 on 2019-07-11 22:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0005_auto_20190711_1724'),
    ]

    operations = [
        migrations.AddField(
            model_name='venta',
            name='precio',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='venta',
            name='total',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
