# Generated by Django 2.2.3 on 2019-08-06 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0012_venta_total_ganancia'),
    ]

    operations = [
        migrations.CreateModel(
            name='Efectivo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Dia', models.IntegerField(blank=True, null=True)),
                ('efectivo_diario', models.IntegerField(blank=True, null=True)),
            ],
        ),
    ]
