# Generated by Django 2.2.3 on 2019-08-06 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0013_efectivo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='efectivo',
            old_name='efectivo_diario',
            new_name='efectivo_billete',
        ),
        migrations.AddField(
            model_name='efectivo',
            name='efectivo_moneda',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
